version: '3'
services:
  react-next-15:
    image: node20:latest
    container_name: react-next-15
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Volumen solo para node_modules, se instalarán dentro del contenedor
    environment:
      - NODE_ENV=development
    command: npm run dev
    working_dir: /app